select * from customer limit 20;

--Calculating Total Revenvue generated by Gender
Select gender, Sum(purchase_amount) as revenue
from customer
group by gender;

--Identifying Which Customer used discount but still spent more than average purchase amount
Select customer_id, purchase_amount
from customer
Where discount_applied = 'Yes' 
and purchase_amount >= (select AVG(purchase_amount) from customer);

 --Identifying Top 5 Products wiyh highest average review rating
select item_purchased, round (AVG (review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Comparing the average product amounts between standard shipping and Express shipping
select shipping_type, round (AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--Indentifying if subcribed customers spend more; comparing average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count (customer_id) as total_customers,
round(AVG(purchase_amount),2) as avg_spend,
round (sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status;

--5 products having highest percentage of purchases with discount applied
select item_purchased,
round(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT (*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
Limit 5;

--segemting customer into New, Returning, and Loyal based on their total number of previous purchases 
--and showing count in each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	End as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Finding if repeat buyers (with more than 5 previous purchases) are likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status;

--Revenue contribution of each age group
Select age_group,
sum (purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

--Connecting customer satisfacting with revenue 
--finding if customers who give high ratings spend more money?
select review_rating,
round (AVG(purchase_amount), 2) AS avg_spend,
round (SUM(purchase_amount), 2) AS total_revenue,
count(*) as total_orders
from customer
group by review_rating
order by review_rating DESC;

--Which season has the highest revenue and orders
select season,
ROUND(SUM(purchase_amount),2) as total_revenue,
COUNT (*)  AS total_orders
from customer
GROUP BY season
ORDER BY total_revenue DESC;

--Finding best category in each season
with season_item_sales as(
select season, item_purchased,
count(*) as total_sold,
ROW_NUMBER() OVER(
PARTITION BY season
ORDER BY COUNT(*) DESC
) AS rank_no
FROM customer
GROUP BY season, item_purchased
)
select season, item_purchased, total_sold
FROM season_item_sales
WHERE rank_no = 1
ORDER BY season;

--Finding which state has highest total sales
select location,
ROUND(SUM(purchase_amount), 2) AS total_revenue,
COUNT(*) AS total_order
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;